/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#261a00",
        "surface-container-highest": "#e5e2e1",
        "surface-container-low": "#f6f3f2",
        "on-tertiary-fixed": "#001e2e",
        "secondary-container": "#fdc003",
        "on-tertiary-container": "#fcfcff",
        "primary-fixed-dim": "#ffb5a0",
        "primary-container": "#ff5722",
        "surface-dim": "#dcd9d9",
        "on-secondary": "#ffffff",
        "outline-variant": "#e4beb4",
        "on-surface": "#1b1c1c",
        "tertiary-container": "#007caf",
        secondary: "#785900",
        "tertiary-fixed": "#c8e6ff",
        "on-background": "#1b1c1c",
        "tertiary-fixed-dim": "#86cfff",
        "on-primary-fixed": "#3b0900",
        surface: "#fcf9f8",
        "secondary-fixed": "#ffdf9e",
        "on-surface-variant": "#5b4039",
        "on-primary-fixed-variant": "#862200",
        "secondary-fixed-dim": "#fabd00",
        tertiary: "#00628c",
        "surface-tint": "#b02f00",
        "surface-container": "#f0eded",
        outline: "#907067",
        "surface-bright": "#fcf9f8",
        "inverse-surface": "#303030",
        "inverse-primary": "#ffb5a0",
        "primary-fixed": "#ffdbd1",
        "on-secondary-container": "#6c5000",
        "on-error": "#ffffff",
        background: "#fcf9f8",
        "on-primary-container": "#541200",
        "inverse-on-surface": "#f3f0ef",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#eae7e7",
        error: "#ba1a1a",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#004c6d",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e5e2e1",
        "on-secondary-fixed-variant": "#5b4300",
        primary: "#b02f00",
        "on-primary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        base: "8px",
        "section-gap": "64px",
        "margin-desktop": "40px",
        "container-max": "1200px",
        "margin-mobile": "16px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        "label-bold": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "price-display": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "label-bold": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "price-display": ["22px", { lineHeight: "24px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
